import Foundation

/// Generates the statusline capture script installed ahead of the user's own
/// `statusLine` command.
///
/// Claude Code pipes a JSON payload to whatever `statusLine.command` names.
/// That payload carries quota and cost, which exist nowhere else on disk —
/// not even the transcript — so Plume must sit in that pipe to see them. The
/// generated script reads stdin once, writes it verbatim (atomically) to
/// `$PLUME_EVENTS_DIR/$PLUME_TASK_ID/$PLUME_TAB_ID.statusline.json`, then runs
/// the chained command with the same stdin and passes its stdout through
/// unchanged, so the user's own statusline looks identical.
///
/// **The capture is conditional; the chain is not.** `settings.json` is global
/// but the three `PLUME_*` variables only exist in a terminal Plume launched,
/// so the script captures nothing and goes straight to the chain everywhere
/// else. Without that guard the user's real statusline disappears from every
/// other terminal.
///
/// Dependency-free and bash-3.2-safe, same rationale as `HookSettingsWriter`.
enum StatuslineCaptureWriter {
    /// `chainCommand` is the user's previous `statusLine.command`, run exactly
    /// as Claude Code would have run it (through `sh -c`, inheriting stdin).
    ///
    /// The capture write happens before the chain runs, and the script exits
    /// 0 regardless of the chain's outcome — a missing or failing chain
    /// target must never blank the user's statusline or fail the hook.
    static func script(chainCommand: String) -> String {
        // Single-quoted so the chain command reaches `sh -c` as one literal
        // argument, not re-parsed by this script's own shell.
        let quotedChain = "'" + chainCommand.replacingOccurrences(of: "'", with: "'\\''") + "'"
        return #"""
        #!/usr/bin/env bash
        # Generated by Plume — captures the statusline payload, then chains to
        # the previous statusLine command with its stdout passed through.
        set -u

        input=$(cat)

        if [ -n "${PLUME_EVENTS_DIR:-}" ] && [ -n "${PLUME_TASK_ID:-}" ] && [ -n "${PLUME_TAB_ID:-}" ]; then
          dir="$PLUME_EVENTS_DIR/$PLUME_TASK_ID"
          mkdir -p "$dir"
          tmp="$dir/$PLUME_TAB_ID.statusline.json.tmp.$$"
          printf '%s' "$input" > "$tmp" && mv -f "$tmp" "$dir/$PLUME_TAB_ID.statusline.json"
        fi

        printf '%s' "$input" | sh -c \#(quotedChain)
        exit 0
        """#
    }

    /// Writes the capture script for `chainCommand`, returning its path.
    /// `chainCommand` is the previously-installed `statusLine.command`.
    @discardableResult
    static func write(chainCommand: String) throws -> URL {
        let url = AppPaths.statuslineScriptFile
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try script(chainCommand: chainCommand).write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: url.path
        )
        return url
    }
}
