import Testing
import Foundation
@testable import Plume

/// How a past conversation is labelled in the resume picker.
///
/// The corpus these rules were drawn from has no `summary` lines at all, so
/// the label comes from `ai-title` when Claude wrote one and the opening
/// prose otherwise.
@MainActor
struct StoredSessionTests {
    /// Built through `JSONSerialization` so a newline or quote in the message
    /// produces a valid line rather than one the reader silently skips.
    private func userLine(_ text: String, isMeta: Bool = false) -> String {
        let object: [String: Any] = [
            "type": "user",
            "isMeta": isMeta,
            "message": ["role": "user", "content": text],
        ]
        let data = try! JSONSerialization.data(withJSONObject: object)
        return String(decoding: data, as: UTF8.self)
    }

    @Test func aiTitleIsPreferredOverTheOpeningMessage() throws {
        let data = Data(([
            userLine("Fix the crash on launch"),
            #"{"type":"ai-title","aiTitle":"Launch crash"}"#,
        ] as [String]).joined(separator: "\n").utf8)

        #expect(SessionJSONLReader.latestAITitle(in: data) == "Launch crash")
        #expect(SessionJSONLReader.firstUserMessage(in: data) == "Fix the crash on launch")
    }

    @Test func theOpeningMessageLabelsAnUntitledSession() {
        let data = Data(userLine("Fix the crash on launch").utf8)
        #expect(SessionJSONLReader.latestAITitle(in: data) == nil)
        #expect(SessionJSONLReader.firstUserMessage(in: data) == "Fix the crash on launch")
    }

    /// A skill body and a slash command's expansion arrive as user lines but
    /// are not what the conversation was about.
    @Test func injectedOpenersAreSkippedInFavorOfRealProse() {
        let data = Data(([
            userLine("<command-name>/review</command-name>"),
            userLine("Caveat: the messages below were generated by a hook", isMeta: true),
            userLine("Actually, let's talk about the sidebar"),
        ] as [String]).joined(separator: "\n").utf8)

        #expect(SessionJSONLReader.firstUserMessage(in: data) == "Actually, let's talk about the sidebar")
    }

    /// A session begun with `/implement-ticket` has no prose at all — the
    /// command is the request, and the rest is tool results.
    @Test func aSlashCommandLabelsASessionWithNoProse() {
        let data = Data(([
            userLine("<command-message>implement-ticket</command-message>\n<command-name>/implement-ticket</command-name>"),
            userLine("<local-command-stdout>done</local-command-stdout>"),
        ] as [String]).joined(separator: "\n").utf8)

        #expect(SessionJSONLReader.firstUserMessage(in: data) == "/implement-ticket")
    }

    @Test func proseStillWinsOverAnEarlierSlashCommand() {
        let data = Data(([
            userLine("<command-name>/review</command-name>"),
            userLine("Actually, let's talk about the sidebar"),
        ] as [String]).joined(separator: "\n").utf8)

        #expect(SessionJSONLReader.firstUserMessage(in: data) == "Actually, let's talk about the sidebar")
    }

    @Test func sidechainLinesAreNotTheConversationsOpening() {
        let data = Data(([
            #"{"type":"user","isSidechain":true,"message":{"role":"user","content":"subagent prompt"}}"#,
            userLine("the real question"),
        ] as [String]).joined(separator: "\n").utf8)

        #expect(SessionJSONLReader.firstUserMessage(in: data) == "the real question")
    }

    @Test func aLongOpeningMessageIsCondensedToOneLine() throws {
        let text = String(repeating: "word ", count: 100) + "\nsecond line"
        let message = try #require(SessionJSONLReader.firstUserMessage(in: Data(userLine(text).utf8)))
        #expect(message.count <= 61)
        #expect(!message.contains("\n"))
        #expect(message.hasSuffix("…"))
    }

    @Test func onlyTheFirstLineOfAMultiLineOpenerIsUsed() throws {
        let text = "Fix the crash on launch\n\nIt happens every time on an M1 Mac."
        let message = try #require(SessionJSONLReader.firstUserMessage(in: Data(userLine(text).utf8)))
        #expect(message == "Fix the crash on launch")
    }

    /// The scan is capped so labelling a directory does not read megabytes
    /// per session; a message past the cap is simply not found.
    @Test func theForwardScanIsBounded() {
        let padding = String(repeating: #"{"type":"file-history-snapshot"}"#, count: 1)
        let data = Data(([padding, userLine("way down here")] as [String]).joined(separator: "\n").utf8)
        #expect(SessionJSONLReader.firstUserMessage(in: data, limit: 8) == nil)
        #expect(SessionJSONLReader.firstUserMessage(in: data) == "way down here")
    }

    /// The title is read from the tail, so a retitle late in a long
    /// conversation is the one that shows.
    @Test func theCurrentTitleIsFoundPastMegabytesOfConversation() throws {
        let directory = URL.temporaryDirectory.appending(path: UUID().uuidString)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let filler = String(
            repeating: #"{"type":"file-history-snapshot","messageId":"x"}"# + "\n",
            count: 40_000
        )
        let path = directory.appending(path: "\(UUID().uuidString).jsonl").path
        try (#"{"type":"ai-title","aiTitle":"First guess"}"# + "\n"
            + filler
            + #"{"type":"ai-title","aiTitle":"What it became"}"#)
            .write(toFile: path, atomically: true, encoding: .utf8)

        let session = try #require(
            SessionJSONLReader.storedSession(atTranscriptPath: path, workingDirectory: "/tmp")
        )
        #expect(session.title == "What it became")
    }

    @Test func aTranscriptWithNoProseFallsBackToTheSessionID() {
        let session = StoredSession(
            sessionID: "b8121543-db01-4501",
            transcriptPath: "/tmp/x.jsonl",
            workingDirectory: "/tmp",
            title: nil,
            firstUserMessage: nil,
            lastModified: .now
        )
        #expect(session.displayTitle == "b8121543")
    }

    // MARK: - On disk

    @Test func aStoredSessionReadsItsIDAndLabelFromTheFile() throws {
        let directory = URL.temporaryDirectory.appending(path: UUID().uuidString)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let id = "3f2b1a44-0000-4000-8000-000000000001"
        let path = directory.appending(path: "\(id).jsonl").path
        try #"{"type":"ai-title","aiTitle":"Resume picker"}"#.write(toFile: path, atomically: true, encoding: .utf8)

        let session = try #require(
            SessionJSONLReader.storedSession(atTranscriptPath: path, workingDirectory: "/Users/me/dev")
        )
        #expect(session.sessionID == id)
        #expect(session.displayTitle == "Resume picker")
        #expect(session.workingDirectory == "/Users/me/dev")
    }

    /// Claude Code leaves empty transcripts behind for sessions that never
    /// produced a line; they cannot be resumed into anything.
    @Test func anEmptyTranscriptIsNotAStoredSession() throws {
        let directory = URL.temporaryDirectory.appending(path: UUID().uuidString)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let path = directory.appending(path: "empty.jsonl").path
        try "".write(toFile: path, atomically: true, encoding: .utf8)

        #expect(SessionJSONLReader.storedSession(atTranscriptPath: path, workingDirectory: "/tmp") == nil)
    }

    @Test func aMissingTranscriptIsNotAStoredSession() {
        #expect(SessionJSONLReader.storedSession(
            atTranscriptPath: "/tmp/\(UUID().uuidString).jsonl", workingDirectory: "/tmp"
        ) == nil)
    }
}

/// The fallback used wherever a first user message stands in for a title,
/// including the resume picker (`StoredSession.displayTitle` reads the same
/// `firstUserMessage`).
struct ShortenedOpeningLineTests {
    @Test func shortTextPassesThroughUnchanged() {
        #expect(SessionJSONLReader.shortenedOpeningLine("Fix the login bug") == "Fix the login bug")
    }

    @Test func onlyTheFirstNonEmptyLineIsKept() {
        let text = "\n\nFix the login bug\nSteps to reproduce: ..."
        #expect(SessionJSONLReader.shortenedOpeningLine(text) == "Fix the login bug")
    }

    @Test func internalWhitespaceIsCollapsed() {
        #expect(SessionJSONLReader.shortenedOpeningLine("Fix   the\tlogin  bug") == "Fix the login bug")
    }

    @Test func longTextTruncatesAtAWordBoundary() {
        let text = "Investigate why the sidebar collapses when a task has more than nine tabs open"
        let shortened = SessionJSONLReader.shortenedOpeningLine(text, maximum: 30)
        #expect(shortened == "Investigate why the sidebar…")
        #expect(shortened.count <= 31)
    }

    /// A single word past the limit has no space to cut at, so the ellipsis
    /// still lands rather than the helper returning nothing.
    @Test func aSingleLongWordIsHardTruncated() {
        let shortened = SessionJSONLReader.shortenedOpeningLine(String(repeating: "a", count: 80), maximum: 10)
        #expect(shortened == String(repeating: "a", count: 10) + "…")
    }

    @Test func emptyTextYieldsEmptyText() {
        #expect(SessionJSONLReader.shortenedOpeningLine("") == "")
    }

    @Test func aWordEndingExactlyAtTheLimitIsKeptWhole() {
        let shortened = SessionJSONLReader.shortenedOpeningLine("aaaa bbbb cccc", maximum: 9)
        #expect(shortened == "aaaa bbbb…")
    }

    /// The nearest space is two words back, which would throw away most of
    /// the 9-character prefix — a hard cut keeps more of it than that would.
    @Test func aWordBoundaryFarFromTheLimitHardTruncatesInstead() {
        let shortened = SessionJSONLReader.shortenedOpeningLine("I https://example.com/a/b/c/d/e/f/g", maximum: 9)
        #expect(shortened == "I https:/…")
    }
}
